spring:
  datasource:
    url: jdbc:h2:tcp://localhost/~/test/tradlinx
    driver-class-name: org.h2.Driver
    username: sa
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create-drop
    database-platform: org.hibernate.dialect.H2Dialect
  
  output:
    ansi:
      enabled: always
  h2:
    console:
      enabled: true
      path: /h2-console
logging:
  level:
    org.hibernate.type: trace
